"use strict";
function e(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function checked(v){return v?" checked":"";}
function renderNotifications(notifications,preferences,options={}){
 const msg=options.message?`<p role="status">${e(options.message)}</p>`:"";
 const items=notifications.length?`<ul>${notifications.map(n=>`<li>${n.read_at?"":"Unread: "}${e(n.message)}${n.bulletin_post_id?` <a href="/community/member/notifications/${e(n.id)}/open">Open conversation</a>`:""}</li>`).join("")}</ul>`:"<p>You have no notifications.</p>";
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Notifications - Open Door Design Community</title><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/community/assets/community.css"></head><body><div class="skip-links"><a href="#main">Skip to main content</a><a href="#primary-navigation">Skip to primary navigation</a></div><header class="banner" aria-labelledby="banner-name"><span id="banner-name" class="visually-hidden">Banner</span></header><nav id="primary-navigation" aria-labelledby="nav-name"><span id="nav-name" class="visually-hidden">Primary navigation</span><ul><li><a href="/community/member/dashboard/">Dashboard</a></li><li><a href="/community/member/bulletin-board/">Bulletin Board</a></li><li><a href="/community/member/directory/">Open Door Directory</a></li><li><a href="/community/member/notifications/" aria-current="page">Notifications</a></li></ul></nav><main id="main" tabindex="-1"><h1>Notifications</h1>${msg}<h2>Recent notifications</h2>${items}<form method="post" action="/community/member/notifications/read"><button type="submit">Mark all notifications as read</button></form><h2>Notification preferences</h2><form method="post" action="/community/member/notifications/preferences"><fieldset><legend>How should we tell you about replies to conversations you own or follow?</legend><div><input id="dashboard-enabled" name="dashboard_enabled" type="checkbox" value="yes"${checked(preferences.dashboard_enabled)}><label for="dashboard-enabled">Show notifications on my Community Dashboard</label></div><div><input id="email-replies-enabled" name="email_replies_enabled" type="checkbox" value="yes"${checked(preferences.email_replies_enabled)}><label for="email-replies-enabled">Email me when someone replies</label></div><div><input id="sms-replies-enabled" name="sms_replies_enabled" type="checkbox" value="yes"${checked(preferences.sms_replies_enabled)}><label for="sms-replies-enabled">Text me when someone replies</label></div><div><label for="sms-phone">Mobile number for text notifications</label><input id="sms-phone" name="sms_phone" type="tel" maxlength="30" value="${e(preferences.sms_phone)}"><p>SMS delivery will begin when the Community SMS provider is connected. Saving a number here does not send a text yet.</p></div></fieldset><button type="submit">Save notification preferences</button></form></main><footer role="contentinfo"><p><a href="https://opendoordesign.org/Accessibility-OpenDoorDesign.html">Accessibility Commitment</a></p></footer></body></html>`;
}
module.exports={renderNotifications};
