"use strict";
function e(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function when(v){return e(new Date(v).toLocaleString("en-US"));}
function renderBulletinBoard(posts, options={}){
 const msg=options.message?`<p role="status">${e(options.message)}</p>`:"";
 const list=posts.length?posts.map(p=>`<article><h2><a href="/community/member/bulletin-board/post/${e(p.id)}/">${e(p.subject)}</a></h2><p>Posted by ${e(`${p.first_name} ${p.last_name}`.trim())} on ${when(p.created_at)}</p><p>${e(p.body).replace(/\n/g,"<br>")}</p><p>${Number(p.reply_count)||0} ${(Number(p.reply_count)||0)===1?"reply":"replies"}. Last activity ${when(p.last_activity_at||p.created_at)}.</p><p><a href="/community/member/bulletin-board/post/${e(p.id)}/">Read and reply</a></p></article>`).join(""):"<p>There are no bulletin board posts yet. You can start the conversation.</p>";
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Bulletin Board - Open Door Design Community</title><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/css/odd-theme.css"><link rel="stylesheet" href="/css/odd-layout.css"><link rel="stylesheet" href="/css/odd-components.css"><link rel="stylesheet" href="/css/odd-utilities.css"><link rel="stylesheet" href="/community/assets/community.css"></head><body><div class="skip-links"><a href="#main">Skip to main content</a><a href="#primary-navigation">Skip to primary navigation</a></div><header class="banner" aria-labelledby="banner-name"><span id="banner-name" class="visually-hidden">Banner</span></header><nav id="primary-navigation" class="primary-nav" aria-labelledby="nav-name"><span id="nav-name" class="visually-hidden">Primary navigation</span><ul><li><a href="/community/member/dashboard/">Dashboard</a></li><li><a href="/community/member/directory/">Open Door Directory</a></li><li><a href="/community/member/bulletin-board/" aria-current="page">Bulletin Board</a></li><li><a href="/community/member/notifications/">Notifications</a></li></ul></nav><main id="main" tabindex="-1"><section class="section"><h1>Community Bulletin Board</h1><p>Share an announcement, question, idea, or invitation with signed-in Community members.</p>${msg}<form method="post" action="/community/member/bulletin-board"><div class="field"><label for="subject">Subject <span class="required-text">required</span></label><input id="subject" name="subject" maxlength="160" required></div><div class="field"><label for="body">Message <span class="required-text">required</span></label><textarea id="body" name="body" maxlength="5000" rows="8" required></textarea></div><button type="submit">Post to Bulletin Board</button></form><h2>Recent posts</h2>${list}</section></main><footer role="contentinfo"><p><a href="https://opendoordesign.org/Accessibility-OpenDoorDesign.html">Accessibility Commitment</a></p></footer></body></html>`;
}
function renderBulletinThread(post,replies,options={}){
 const msg=options.message?`<p role="status">${e(options.message)}</p>`:"";
 const replyList=replies.length?`<ol>${replies.map(r=>`<li><article><h3>Reply from ${e(`${r.first_name} ${r.last_name}`.trim())}</h3><p>${e(r.body).replace(/\n/g,"<br>")}</p><p>Posted ${when(r.created_at)}</p></article></li>`).join("")}</ol>`:"<p>No replies yet.</p>";
 const followControl=options.isOwner?`<p>You started this conversation, so replies are automatically included in your notification preferences.</p>`:`<form method="post" action="/community/member/bulletin-board/post/${e(post.id)}/follow"><input type="hidden" name="action" value="${options.isFollowing?"unfollow":"follow"}"><button type="submit">${options.isFollowing?"Stop following this conversation":"Follow this conversation"}</button></form><p>${options.isFollowing?"You are following this conversation. New replies use your notification preferences.":"Follow this conversation if you want notifications when other members reply."}</p>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${e(post.subject)} - Community Bulletin Board</title><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/css/odd-theme.css"><link rel="stylesheet" href="/css/odd-layout.css"><link rel="stylesheet" href="/css/odd-components.css"><link rel="stylesheet" href="/css/odd-utilities.css"><link rel="stylesheet" href="/community/assets/community.css"></head><body><div class="skip-links"><a href="#main">Skip to main content</a><a href="#primary-navigation">Skip to primary navigation</a></div><header class="banner" aria-labelledby="banner-name"><span id="banner-name" class="visually-hidden">Banner</span></header><nav id="primary-navigation" aria-labelledby="nav-name"><span id="nav-name" class="visually-hidden">Primary navigation</span><ul><li><a href="/community/member/dashboard/">Dashboard</a></li><li><a href="/community/member/directory/">Open Door Directory</a></li><li><a href="/community/member/bulletin-board/" aria-current="page">Bulletin Board</a></li><li><a href="/community/member/notifications/">Notifications</a></li></ul></nav><main id="main" tabindex="-1"><h1>${e(post.subject)}</h1>${msg}<article><p>Posted by ${e(`${post.first_name} ${post.last_name}`.trim())} on ${when(post.created_at)}</p><p>${e(post.body).replace(/\n/g,"<br>")}</p></article><h2>Follow this conversation</h2>${followControl}<h2>Replies</h2>${replyList}<h2>Reply to this conversation</h2><form method="post" action="/community/member/bulletin-board/post/${e(post.id)}/reply"><div class="field"><label for="reply-body">Reply <span class="required-text">required</span></label><textarea id="reply-body" name="body" maxlength="5000" rows="7" required></textarea></div><button type="submit">Post reply</button></form><p><a href="/community/member/bulletin-board/">Return to Bulletin Board</a></p></main><footer role="contentinfo"><p><a href="https://opendoordesign.org/Accessibility-OpenDoorDesign.html">Accessibility Commitment</a></p></footer></body></html>`;
}
module.exports={renderBulletinBoard,renderBulletinThread};
